apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world-app
  namespace: default
  labels:
    app: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
